homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  auth_providers:
    - type: homeassistant
    # uncomment this to enable backwards compatible API password support
    - type: legacy_api_password

  customize: !include_dir_merge_named customize

# mqtt_statestream:
#   base_topic: homeassistant
#   publish_attributes: true
#   publish_timestamps: true

# Enables the frontend
frontend:

# Enables iOS
ios:
  push:
    categories:
      - name: Onderweg naar huis
        identifier: 'on_your_way_home'
        actions:
          - identifier: 'YES'
            title: 'Ja'
          - identifier: 'NO'
            title: 'Nee'

http:
  base_url: home.ashwinvandijk.nl
  api_password: !secret http_password
#  ssl_certificate: /etc/letsencrypt/live/home.ashwinvandijk.nl/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/home.ashwinvandijk.nl/privkey.pem
  cors_allowed_origins:
    - http://localhost:3000

mqtt:
  broker: 10.10.1.1
  port: 1883
  client_id: homeassistant
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

# Checks for available updates
updater:

config:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  purge_interval: 2
  purge_keep_days: 4
  db_url: !secret recorder_url

influxdb:
  host: 127.0.0.1

history:
  use_include_order: True
  include:
      domains:
        - sensor
        - light
        - switch
        - binary_sensor

# Logs
logger:
  default: warn

# View all events in a logbook
logbook:

# Track the sun
sun:

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
camera: !include_dir_merge_list camera
climate: !include_dir_merge_list climate
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
intent_script: !include_dir_merge_named intent_script
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
plant: !include_dir_merge_named plant
remote: !include_dir_merge_list remote
scene: !include_dir_merge_list scene
script: !include_dir_named script
sensor: !include_dir_merge_list sensor
snips: !include_dir_merge_list snips
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone

# Zwave
zwave:
  usb_path: /dev/zwave

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
