- alias: Lightning - Bathroom - On
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence, binary_sensor.sensor_2
      to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.level
        state: 'off'
      - condition: state
        entity_id: input_select.mode
        state: 'Normaal'

  action:
    service: light.turn_on
    data:
      entity_id: light.level
      brightness: 255

# ---------- #

- alias: Lightning - Bathroom - On (Night)
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.level
        state: 'off'
      - condition: state
        entity_id: input_select.mode
        state: 'Nacht'

  action:
    service: light.turn_on
    data:
      entity_id: light.level
      brightness: 3

# ---------- #

- alias: Lightning - Bathroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.level
