# --- Normal mode --- #

- alias: Lightning - Livingroom - On
  trigger:
  - platform: state
    entity_id: input_boolean.livingroom_presence, binary_sensor.livingroom_radar_01, input_boolean.livingroom_auto
    to: 'on'
  - platform: state
    entity_id: binary_sensor.livingroom_dark
    to: 'on'
    for:
      minutes: 3


  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.mode
        state: 'Normaal'


      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: 'on'
        for:
          minutes: 3
      - condition: state
        entity_id: input_boolean.livingroom_presence
        state: 'on'
      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_lights_dimmed

# --- Night mode --- #

- alias: Lightning - Livingroom - Night
  trigger:
  - platform: state
    entity_id: input_boolean.livingroom_presence, binary_sensor.livingroom_dark, input_boolean.livingroom_auto
    to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.mode
        state: 'Nacht'


      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: 'on'
      - condition: state
        entity_id: input_boolean.livingroom_presence
        state: 'on'
      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_lights_night

# --- Turn off --- #

- alias: Lightning - Livingroom - Off
  trigger:
  - platform: state
    entity_id: input_boolean.livingroom_presence
    to: 'off'
  - platform: state
    entity_id: binary_sensor.livingroom_dark
    to: 'off'
    for:
      minutes: 7

  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.livingroom_auto
      state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_lights_off