- platform: 'bayesian'
  name: 'In bed'
  prior: 0.45
  probability_threshold: 0.95
  observations:
    - entity_id: 'group.presence'
      prob_given_true: 0.9
      prob_given_false: 0.10
      platform: 'state'
      to_state: 'off'
    - entity_id: 'switch.computer'
      prob_given_true: 0.3
      platform: 'state'
      to_state: 'off'
    - entity_id: 'input_boolean.bedroom_presence'
      prob_given_true: 0.9
      platform: 'state'
      to_state: 'on'
