- platform: limitlessled
  bridges:
    - host: 10.10.1.3
      groups:
        - number: 1
          name: hal
          type: rgbw

        - number: 1
          name: keuken
          type: rgbww



        - number: 2
          name: bol
          type: rgbww
          
        - number: 3
          name: bed
          type: rgbw
