- alias: Huis - Scene - Thuis
  trigger:
    platform: state
    entity_id: binary_sensor.home
    to: 'on'

  action:
    service: homeassistant.turn_on
    entity_id: scene.home

- alias: Huis - Scene - Weg
  trigger:
    platform: state
    entity_id: binary_sensor.home
    to: 'off'
    for:
      minutes: 5

  action:
    service: homeassistant.turn_on
    entity_id: scene.away
