- alias: Woonkamer - Scenes
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.livingroom_scene

  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.livingroom_scene", "Aan") %}
            scene.livingroom__lights__level_4
          {% elif is_state("input_select.livingroom_scene", "Normaal") %}
            scene.livingroom__lights__level_3
          {% elif is_state("input_select.livingroom_scene", "Nacht") %}
            scene.livingroom__lights__level_1
          {% elif is_state("input_select.livingroom_scene", "Uit") %}
            scene.livingroom__lights__level_0
          {% endif %}

#    - service: input_select.select_option
#      data:
#        entity_id: input_select.livingroom_scene
#        option: "Selecteer..."


#- alias: Woonkamer - Auto - On
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: input_select.livingroom_scene
#
#  condition:
#    condition: template
#    value_template: '{{ trigger.to_state.state == "Automatisch" }}'
#
#  action:
#    service: homeassistant.turn_on
#    data:
#      entity_id: input_boolean.livingroom_auto
#
#
#- alias: Woonkamer - Auto - Off
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: input_select.livingroom_scene
#
#  condition:
#    condition: template
#    value_template: '{{ trigger.to_state.state != "Automatisch" and trigger.to_state.state != "Selecteer..." }}'
#
#  action:
#    service: homeassistant.turn_off
#    data:
#      entity_id: input_boolean.livingroom_auto

