- platform: mqtt
  name: "bedroom speakers"
  state_topic: "sonoff/1/stat"
  command_topic: "sonoff/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "kitchen speakers"
  state_topic: "sonoff/2/stat"
  command_topic: "sonoff/2"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "computer"
  state_topic: "sonoff/3/stat"
  command_topic: "sonoff/3"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "trap"
  state_topic: "sonoff/4/stat"
  command_topic: "sonoff/4"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "coffee power"
  state_topic: "coffeebot/stat"
  command_topic: "coffeebot"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: false