- alias: House - Mode - Night
  trigger:
    platform: time
    at: '23:30:00'
  
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.mode
        state: 'Normaal'

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode
      option: 'Nacht'


- alias: House - Mode - Normal
  trigger:
    platform: time
    at: '6:30:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.mode
        state: 'Nacht'

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode
      option: 'Normaal'