- alias: Huis - Mode - Nacht
  trigger:
    platform: time
    at: '00:30:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.mode
        state: 'Normaal'

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode
      option: 'Nacht'


- alias: Huis - Mode - Normaal
  trigger:
    platform: time
    at: '7:30:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.mode
        state: 'Nacht'

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode
      option: 'Normaal'
