- alias: Climate - Ventilation On
  trigger:
    platform: time
    at: '03:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_2