- platform: miflora
  mac: "C4:7C:8D:62:05:2C"
  name: Flower 1
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - conductivity
    - battery

- platform: miflora
  mac: "C4:7C:8D:62:02:79"
  name: Flower 2
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - conductivity
    - battery

- platform: miflora
  mac: "C4:7C:8D:62:05:2C"
  name: Flower 3
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - conductivity
    - battery