- platform: 'bayesian'
  name: 'Home'
  prior: 0.25
  probability_threshold: 0.95
  observations:
    - entity_id: 'group.presence'
      prob_given_true: 1
      prob_given_false: 0
      platform: 'state'
      to_state: 'on'
    - entity_id: 'switch.computer'
      prob_given_true: 0.75
      prob_given_false: 0
      platform: 'state'
      to_state: 'on'

