- alias: Aanwezigheid - Slaapkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_3
      to: 'on'

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bedroom_presence

# ---------- #

- alias: Aanwezigheid - Slaapkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_3
    to: 'off'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bedroom_presence
