- alias: Aanwezigheid - Toilet - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_4
      to: 'on'

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.toilet_presence

# ---------- #

- alias: Aanwezigheid - Toilet - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_4
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.toilet_presence
